---
title: "mariners suck"
author: "Kobe Sarausad"
date: "5/13/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Load packages
library(tidyverse)
library(rvest)
library(ggrepel)
library(cowplot)

read.csv("2020eve/2020SEA.csv")
```

```{r}
mlb_colors <- read.csv("https://raw.githubusercontent.com/glamp/mlb-payroll-and-wins/master/team-colors.csv")

mlb_colors[15, 2] <- "MIA"

std_bat_2021 <- read_html("https://www.baseball-reference.com/leagues/MLB/2021.shtml") %>% 
  html_table() %>% 
  .[[1]] %>% 
  head(30)

std_bat_col <- left_join(std_bat_2021, mlb_colors, by = c("Tm" = "tm"))

pitch_2021 <- read_html("https://www.baseball-reference.com/leagues/MLB/2021.shtml") %>% 
  html_nodes("#all_teams_standard_pitching") %>% 
  html_nodes(xpath = 'comment()') %>% 
  html_text() %>% 
  read_html() %>% 
  html_nodes("#div_teams_standard_pitching") %>% 
  html_table() %>% 
  .[[1]] %>% 
  head(30)

pitch_2021[c(2:36)] <- sapply(pitch_2021[c(2:36)], as.numeric)

std_bat_2021[c(2:29)] <- sapply(std_bat_2021[c(2:29)], as.numeric)

std_pitch_col <- left_join(pitch_2021, mlb_colors, by = c("Tm" = "tm"))

# std_bat_2021_svd <- svd(std_bat_2021[c(2:29)])
# 
# svd_teams <- data.frame(
#   "x" = std_bat_2021_svd$u[, 1],
#   "y" = std_bat_2021_svd$u[, 1],
#   "tm" = std_bat_2021$Tm
# )

# svd_teams %>% 
#   ggplot(aes(x = x, y = y, label = tm)) +
#   geom_point() + 
#   geom_text_repel(nudge_y = 0.005)

mlb_colors$team_short <- ifelse(mlb_colors$team_name == "Los Angeles Angels of Anaheim", "angels", str_to_lower(str_split(mlb_colors$team_name, " ")[[1]][length(str_split(mlb_colors$team_name, " "))]))

team_short <- c()

for (team in mlb_colors$team_name) {
  if (team == "Los Angeles Angels of Anaheim") {
    team_short <- append(team_short, "angels")
  } else if (team == "Boston Red Sox") {
    team_short <- append(team_short, "redsox")
  } else if (team == "Chicago White Sox") {
    team_short <- append(team_short, "whitesox")
  } else if (team == "Toronto Blue Jays") {
    team_short <- append(team_short, "bluejays")
  } else {
    team_short <- append(team_short, str_to_lower(str_split(team, " ")[[1]][length(str_split(team, " ")[[1]])]))
  }
}

mlb_colors$team_short <- team_short

std_bat_full <- left_join(std_bat_2021, mlb_colors, by = c("Tm" = "tm"))

std_bat_full$logo <- sprintf("logos/%s.png", std_bat_full$team_short)

std_bat_full <- std_bat_full[order(-std_bat_full$OBP), ]

plot <- std_bat_full %>% 
  ggplot() +
  geom_bar(aes(x = reorder(Tm, -OBP), y = OBP, fill = Tm), width = 0.8, stat = "identity") +
  scale_fill_manual(values = std_bat_full$team_color) +
  theme_minimal() +
  theme(legend.position = "none",
        plot.title = element_text(size = 25, color = "#696969"),
        axis.title.x = element_blank(),
        text = element_text(family = "mono"),
        plot.background = element_rect(fill = "#F9F9F9", color = "#F9F9F9"),
        panel.background = element_rect(fill = "#F9F9F9", color = "#F9F9F9"),
        plot.caption = element_text(color = "#696969")) +
  labs(title = "Batting Averages 2021", caption = "https://www.baseball-reference.com/leagues/MLB/2021.shtml")

ggsave("sux.png", width = 12, height = 5, plot)

plotimage <- axis_canvas(plot, axis = "x")

for (i in nrow(std_bat_full)) {
  print(std_bat_full[i, "logo"])
  plotimage <- plotimage + 
    draw_image(file.path(std_bat_full[i, "logo"]), x = i, scale = 0.5)
}

ggdraw(insert_xaxis_grob(plot, plotimage))

std_pitch_col %>% 
  ggplot() +
  geom_point(aes(x = SO, y = R, color = Tm)) +
  scale_color_manual(values = std_pitch_col$team_color) +
  theme_minimal() +
  theme(legend.position = "none",
        plot.title = element_text(size = 20, color = "#696969"),
        text = element_text(family = "mono"),
        plot.background = element_rect(fill = "#F9F9F9", color = "#F9F9F9"),
        panel.background = element_rect(fill = "#F9F9F9", color = "#F9F9F9"),
        plot.caption = element_text(color = "#696969")) +
  labs(x = "Hits", y = "Runs", title = "Hits vs Runs Given Up 2021", caption = "https://www.baseball-reference.com/leagues/MLB/2021.shtml")

order(std_pitch_col$H)
```

```{r team hits}
result <- data.frame()

for (year in 2016:2021) {
  url <- sprintf("https://www.baseball-reference.com/teams/tgl.cgi?team=SEA&t=b&year=%s", year)
  
  table <- url %>% 
    read_html() %>% 
    html_nodes("#div_team_batting_gamelogs") %>% 
    html_table() %>% 
    .[[1]] %>% data.frame()
  
  table <- table %>% 
    mutate(year = year)
  
  result <- rbind(result, table)
}

result[c(7:30)] <- sapply(result[c(7:30)], as.numeric)

result %>% 
  filter(Thr != "Thr") %>% 
  group_by(year, Thr) %>% 
  summarize(hits = mean(H), runs = mean(R), hr = mean(HR))

```

```{r}
adv_batting <- read.csv("swing2021.csv")

adv_batting$team_id <- as.factor(adv_batting$team_id)

adv_batting %>% 
  group_by(team_id) %>% 
  summarize(chase = sum(runs_chase))

adv_bat_svd <- svd(adv_batting[, 7:12])

bat_svd_u <- data.frame("x" = adv_bat_svd$u[,1],
                        "y" = adv_bat_svd$u[,2],
                        "team_id" = adv_batting$team_id)

ggplot(bat_svd_u) +
  geom_point(aes(x = x, y = y, color = team_id))
```
